### ISSUE TITLE
希望草稿區每一篇文章最上面都有提示

### ISSUE THREAD

**Issue by pm5** [watchout-tw/blog.citizenedu.tw#11]
「投稿區」http://community.citizenedu.tw/c/41-category

提示

> 這是修改中的文章，歡迎大家提供意見

**Comment by pm5** [comment]
我可以在草稿區文章上面顯示提示。不過提示的內文大概要放在[這裡](http://community.citizenedu.tw/t/topic/10) 。這篇規則說明好像也有點舊了，能不能先把它修改到目前的版本？

**Comment by pm5** [comment]
上面寫的烙哲學投稿區的說明。一般投稿區的說明大概要放在[這裡](http://community.citizenedu.tw/t/topic/1117)。

**Comment by ghost** [comment]
This issue was moved to watchout-tw/discourse#3
