### ISSUE TITLE
單一文章頁面，加上徵稿宣傳圖片

### ISSUE THREAD

**Issue by ghost** [watchout-tw/blog.citizenedu.tw#13]
- 放在作者介紹後面，一樣在白色區塊
- 一張圖片就可以了（坐等朱家安給我圖片）
- 連到：http://blog.citizenedu.tw/posts/938/

**Comment by ghost** [comment]
目前滑鼠移上去沒有做效果。

<img width="1232" alt="2015-09-01 17 51 52" src="https://cloud.githubusercontent.com/assets/3395905/9601185/8ce0ee76-50d2-11e5-93ae-fa2fd0ebae0c.png">

<img width="399" alt="2015-09-01 17 52 15" src="https://cloud.githubusercontent.com/assets/3395905/9601193/971fbbc4-50d2-11e5-8564-265ab203ddd9.png">

**Comment by aging29** [comment]
覺得ok
再麻煩更新～感謝

**Comment by ghost** [comment]
麻煩 pm5 更新，謝謝
