### ISSUE TITLE
客製化摘要的功能

### ISSUE THREAD

**Issue by pm5** [watchout-tw/blog.citizenedu.tw#25]
有些文章比較合適的摘要其實在最後幾段，或是編輯要自己寫。希望提供客製化摘要的功能，但格式還沒想好。

**Comment by aging29** [comment]
客製化摘要是不是可以跟編輯導讀合併？

**Comment by pm5** [comment]
那就放編輯導讀試試看。等 #26 做好來放。

**Comment by ghost** [comment]
This issue was moved to watchout-tw/discourse#8
