### ISSUE TITLE
載入更多設定

### ISSUE THREAD

**Issue by aging29** [watchout-tw/blog.citizenedu.tw#37]
http://blog.citizenedu.tw/

部落格最新文章列表目前一次會顯示二十篇，
但文章已多於二十篇，按了「載入更多」卻沒有反應。

**Comment by ghost** [comment]
第一次顯示 10 篇，每按一次「顯示更多」，要多顯示 10 篇。
沒有文章時「載入更多」按鈕消失。

**Comment by pm5** [comment]
跟 #44 重複了

**Comment by ghost** [comment]
目前寫的載入更多不是「第一次顯示 10 篇，每按一次「顯示更多」，要多顯示 10 篇。」
所以再打開。
