### ISSUE TITLE
部落格文章未顯示

### ISSUE THREAD

**Issue by aging29** [watchout-tw/blog.citizenedu.tw#39]
http://community.citizenedu.tw/t/mg149/1308
http://community.citizenedu.tw/t/p/1307
http://community.citizenedu.tw/t/topic/1273

目前交誼廳這三篇文章run update後沒有顯示在部落格上
再麻煩pm5可以的話先處理，尤其是前兩篇，因為是時事文章所以比較急一些

**Comment by pm5** [comment]
fixed by 522886e56a93d9b683d210f410f471e435d18b18

**Comment by aging29** [comment]
http://community.citizenedu.tw/t/topic/1273

目前這篇文章還是沒有顯示在觀點懶人包的專欄裡

**Comment by pm5** [comment]
是因為觀點懶人包專欄未開啟。
fixed by 0f7e4379e1f1a6264c6a2449cc7c5be23100201a
