### ISSUE TITLE
把「載入更多」掛上去

### ISSUE THREAD

**Issue by pm5** [watchout-tw/blog.citizenedu.tw#44]
webpack 另外 build 一個 load_more.js 在 client-side 掛到那個 DOM element 上就好了，跟 comment.js 的掛法一樣。

**Comment by ghost** [comment]
在 soidid-dev 改了一個初版
不過...
1. 不知道這樣會不會影響 og
2. 因為是 client side 才載入，所以顯示的速度會慢，而且一開始 posts 會跳動。整體來說，我不確定這樣的 ux 有比較好（限量顯示 20 則感覺還比較好？XD）

**Comment by aging29** [comment]
posts會跳動的問題好像比較嚴重，這部分多花些時間是有辦法解決的嗎？
如果能夠解決的話，完善好再推上來也可以。
