### ISSUE TITLE
專欄第二頁以後的 post 沒有抓

### ISSUE THREAD

**Issue by ghost** [watchout-tw/blog.citizenedu.tw#48]
https://github.com/watchout-tw/blog.citizenedu.tw/blob/master/script/update-posts.es6

**Comment by walkingice** [comment]
https://github.com/watchout-tw/blog.citizenedu.tw/blob/master/script/update-posts.es6#L14

<code>
.get(${columns[name].link}.json)
</code>
預設會抓某個 category 的 json 檔，好比 http://community.citizenedu.tw/c/9-category.json

這個 api 相當於 http://community.citizenedu.tw/c/9-category.json?page=0

接著只會產生 page 0 裡面所紀錄的文章。如果要正確解掉，應該是要反覆檢查有無 more_topics_url，直到抓完最後一頁
