### ISSUE TITLE
註冊交誼廳email 錯誤訊息

### ISSUE THREAD

**Issue by aging29** [watchout-tw/blog.citizenedu.tw#50]
目前交誼廳註冊新帳號時，會出現email相關的錯訊息

![screen shot 2015-12-23 at 4 42 03 pm](https://cloud.githubusercontent.com/assets/8164369/11973973/9f2b4060-a99a-11e5-9c23-d90ab0b03825.png)

**Comment by ghost** [comment]
This issue was moved to watchout-tw/discourse#9
