### ISSUE TITLE
自動更新功能

### ISSUE THREAD

**Issue by aging29** [watchout-tw/blog.citizenedu.tw#6]
需要公民學院交誼廳對部落格的自動更新功能，希望可以十分鐘內一次，或是如果不會造成嚴重負擔，
可以隨時同步更新。

**Comment by pm5** [comment]
- 1 分鐘更新一次
- 用 DitigalOcean 主機跑 update script

**Comment by pm5** [comment]
設定好了，一分鐘更新一次。不過這個作法還是有點勉強，我可能會再看看能不能有新文章就 trigger build。

**Comment by pm5** [comment]
設定好了，一分鐘更新一次。不過這個作法還是有點勉強，我可能會再看看能不能有新文章就 trigger build。
