### ISSUE TITLE
影片無法顯示

### ISSUE THREAD

**Issue by aging29** [watchout-tw/blog.citizenedu.tw#8]
交誼廳編輯時使用嵌入碼的影片無法在完成編輯時的交誼廳文章中顯示
如果是使用網址則可以在文章中顯示
但兩者均無法在部落格中顯示出來

交誼廳：http://community.citizenedu.tw/t/topic/1236/1
部落格：http://blog.citizenedu.tw/posts/1236/

**Comment by ghost** [comment]
This issue was moved to watchout-tw/discourse#2
