### ISSUE TITLE
圖片授權字樣

### ISSUE THREAD

**Issue by aging29** [watchout-tw/blog.citizenedu.tw#9]
安安發現之前討論的圖片授權字樣和連結還沒放上去。
公民學院來自別人授權的圖目前整理在這邊：
https://watchouttw.hackpad.com/s1Gk5FgkOXS

**Comment by pm5** [comment]
See http://blog.citizenedu.tw/columns/%E6%AD%B7%E5%8F%B2%E5%AD%B8%E6%9F%91%E4%BB%94%E5%BA%97/

**Comment by aging29** [comment]
http://blog.citizenedu.tw/columns/歷史學柑仔店/
這張專欄圖由歷史學柑仔店提供，所以不用加上陳小冠的授權連結

另外，歷史學柑仔店、菜市場政治學、巷仔口社會學等三個專欄的文章預設圖（單篇文章上面的橫幅圖片）希望比照現在的方式加上授權

如下圖
![screen shot 2015-09-09 at 11 33 38 am](https://cloud.githubusercontent.com/assets/8164369/9752854/bca024b8-56e7-11e5-9956-5c16ebb8658c.png)

**Comment by pm5** [comment]
改好了
